### ISSUE TITLE
Thank you for your work, but I'll give you some advice.

### ISSUE THREAD

**Issue by songhtdo** [shaovoon/csv_stream#1]
1.  建议考虑一下性能，比如重复利用字符串时，建议使用clear()，而不是=""；
2.  建议删除一些重复代码，比如unescape/num_of_delimiter/get_delimited_str.

**Comment by shaovoon** [comment]
谢谢您的反馈，我会好好考虑你的建议。

**Comment by songhtdo** [comment]
静候佳音。
